### ISSUE TITLE
html fragments doesn't work in a match branch

### ISSUE THREAD

**Issue by Madoshakalaka** [its-the-shrimp/yew-html-ext#4]
```rs
html!{
  match ... {
    A::AA =>{
      <>
        <div/>
        <div/>
      </>
    }
    A::BB =>{
      <div/>
    }
  }
}
```
doesn't compile. wrapping the first branch in `{}` doesn't help either. You have to wrap it in `html!{}`

**Comment by its-the-shrimp** [comment]
Removing the `{}` solves this, as the braces in `html!` are an entry point for Rust code inside HTML

**Comment by Madoshakalaka** [comment]
:exploding_head: thanks
